 eureka:
    instance:
      hostname: localhost
    client:
      registerWithEureka: true
      fetchRegistry: true
      serviceUrl:
        defaultZone: "http://20.193.246.195:9100/service-registry/eureka/"
