 eureka:
    instance:
      hostname: localhost
    client:
      registerWithEureka: true
      fetchRegistry: true
      serviceUrl:
        defaultZone: http://localhost:9100/service-registry/eureka/
